import React from "react";
import "./Announcements.css";
import { FaDownload } from "react-icons/fa";

const Announcements = () => {
  const announcements = [
    "Ola Electric Mobility Limited response to the clarification sought by BSE dated October 20, 2025.",
    "Ola Electric Mobility Limited response to the clarification sought by the NSE dated October 20, 2025.",
    "Intimation of RTA certificate under regulation 74 of SEBI (Depositories and Participants) Regulation, 2018 for the quarter ended September 30, 2025",
    "General Intimation of new product launch dated October 14, 2025",
    "Intimation of social media communication by Chairman & Managing Director of the Company dated October 14, 2025",
    "Disclosure regarding product launch dated October 16, 2025",
    "Ola Launches Ola शक्ति; enters India’s 1 Lakh Cr Battery Energy Storage Systems (BESS) market dated October 16, 2025",
    "General Intimation regarding product launch dated October 15, 2025",
    "Intimation of allotment of OCRPS by Ola Electric Technologies Private Limited a Material Wholly Owned Subsidiary of the Company",
    "Intimation of change in email address of MUFG Intime India Private Limited, Registrar and Share Transfer Agent of the Company dated October 07, 2025",
    "Intimation of Press Release titled “Ola Electric Becomes India's First Automotive OEM to Get Government Certification For its In-House Developed Ferrite Motor” dated October 06, 2025.",
    "Intimation of Trading Window Closure dated September 30, 2025.",
    "Intimation of investment by Ola Cell Technologies Private Limited a Material Wholly Owned Subsidiary of the Company.",
    "Intimation of raising of funds by Issuance of Securities by Ola Electric Technologies Private Limited a Material Wholly Owned Subsidiary of the Company.",
    "Ola Electric's Muhurat Mahotsav Inventory Sells Out in Just 5 Minutes on Day 1",
    "Ola Electric Launches Ola Celebrates India Campaign; Introduces Muhurat Mahotsav with EVs now starting at ₹49,999",
    "Ola Electric achieves 1 million production milestone dated September 16, 2025",
    "Intimation of Contact details of authorised KMPs to determine materiality event or information and its disclosure to the Stock Exchange dated September 12, 2025.",
    "Intimation of Appointment of Company Secretary and Compliance Officer dated September 12, 2025.",
    "Ola Electric Mobility Limited response to the clarification sought by the NSE dated September 08, 2025.",
    "Ola Electric Mobility Limited response to the clarification sought by BSE dated September 08, 2025",
    "Intimation of schedule of proposed participation in Investor / Analyst Meetings dated August 30, 2025",
    "Intimation of Proceedings of the 08th Annual General Meeting of the Company held on August 22, 2025.",
    "Intimation of the Scrutinizer’s Report of the 08th Annual General Meeting of the Company Held on August 22, 2025",
    "Intimation of the Voting Results of the 08th Annual General Meeting of the Company held on August 22, 2025",
    "Intimation of Appointment of Secretarial Auditors of the Company dated August 23, 2025",
    "Ola Electric secures PLI certification for its Gen 3 Scooter Portfolio; profitability to get a boost from Q2 FY26 onwards",
    "Intimation of Shareholders communication dated August 16, 2025",
    "Ola Electric Showcases 'India Inside' Vision at संकल्प (Sankalp) 2025",
    "Intimation of New Product Launch dated August 15, 2025.",
    "Intimation of press note on Sankalp 2025 dated August 05, 2025",
    "Intimation of tweet by founder and Chairman & Managing Director of the Company on Sankalp 2025 dated August 05, 2025",
    "Outcome of Board Meeting dated July 25, 2025.",
    "Intimation of Newspaper Publication of Q1 FY26 Financial Results.",
    "Intimation of RTA Certificate under Regulation 74 of SEBI DP Regulations dated July 15, 2025.",
    "Intimation of Monitoring Agency Report for the quarter ended June 30 2025 dated July 15, 2025.",
    "Intimation of the transcript of the earnings conference call with analysts/investors held on July 14, 2025 dated July 15, 2025",
    "Outcome of Board Meeting dated July 14, 2025.",
    "Shareholders letter for Q1 FY26 dated July 14, 2025.",
    "KPI data book for Q1 FY26 dated July 14, 2025.",
    "Press Release: Ola Electric's Revenue Increases by 35.5% QoQ; Auto Business Turns EBITDA Positive in June 2025 dated July 14, 2025.",
    "Intimation of Investors Presentation for Q1 FY26 dated July 14, 2025.",
    "Intimation of Audio link of Investors conference call for Q1 FY26 dated July 14, 2025.",
    "Press Release-Ola Electric Announces Mass Roll-Out of MoveOS 5; The Biggest Software Upgrade Yet",
    "Intimation of Board Meeting to consider and approve unaudited financial results for first quarter ended June 30, 2025 dated July 08, 2025.",
    "Intimation of scheduled earnings conference call with analysts and investors on Monday, July 14, 2025 dated July 08, 2025.",
    "Intimation of Trading Window Closure dated June 30, 2025.",
    "Intimation of Contact details of authorised KMPs to determine materiality event or information and its disclosure dated June 13, 2025.",
    "Intimation of Resignation of Company Secretary and Compliance Officer dated June 13, 2025.",
    "Intimation of Participation in Investor Meeting dated 17.06.2025.",
    "Outcome of Board Meeting dated May 29, 2025.",
    "Shareholders letter for Q4 FY25 dated May 29, 2025.",
    "KPI data book for Q4 FY25 dated May 29, 2025.",
    "Intimation of Investors Presentation for Q4 FY 25 dated May 29, 2025.",
    "Intimation of Audio link of Investors meet for Q4 FY 25 dated May 29, 2025.",
    "Intimation of Outcome/transcript of Investors Meet for Q4 FY 25 dated May 30, 2025.",
    "Intimation of submission of newspaper advertisement of Financial Results Q4 and Financial Year ended March 31, 2025.",
    "Intimation of updated Invitation / Registration Link for the Earnings Conference Call dated May 27, 2025.",
    "Intimation of schedule earnings conference call with analysts and investors on Thursday, May 29, 2025 dated May 26, 2025.",
    "Intimation of Board Meeting to consider and approve Audited Financial Results for Fourth Quarter and Financial Year ended March 31, 2025 dated May 26, 2025.",
    "Outcome of Board Meeting held on May 22, 2025.",
    "Intimation of tweet by founder and Chairman & Managing Director of the Company on delivery of Roadster X dated May 20, 2025.",
    "Monitoring Agency report for quarter ended March 31, 2025 dated May 15, 2025.",
    "Intimation of Board Meeting to consider and approve raising of funds proposal dated May 19, 2025.",
    "Ola Electric Mobility Limited response to the clarification sought by the NSE dated May 5, 2025.",
    "Ola Electric Mobility Limited response to the clarification sought by BSE dated May 5, 2025.",
    "Clarification on Media articles of Ola Electric Mobility Limited 02.05.2025.",
    "Initial Disclosure of Large Corporate 30.04.2025.",
    "General update on deliveries of Roadster X-30.04.2025.",
    "Ola Electric Mobility Limited response to the clarification sought by the NSE dated April 25, 2025.",
    "Ola Electric Mobility Limited response to the clarification sought by BSE dated April 25, 2025.",
    "Certificate under Regulation 74 of SEBI(DP) Regulations, 2018 for the quarter ended March 31, 2025.",
    "Press Release: Ola Brings in The Next Phase of Electric Revolution; Rolls Out First Roadster X from Futurefactory",
    "Clarification on February 2025 Sales and Rumor Verification.",
    "Press Release: Ola Electric announces #HyperDelivery; rolls out same day registration and delivery of vehicles.",
    "Intimation of Investors Presentation dated April 1, 2025",
    "Ola Electric registers 3,44,005 units in FY25; maintains leadership position with 30% market share.",
    "Intimation of Monthly business update for March 2025",
    "Intimation of Closure of Trading Window for Quarter and Financial Year ended March 31, 2025",
    "Outcome of Board Meeting dated March 30, 2025",
    "Media Statement of Ola Electric Mobility Limited dated March 25, 2025.",
    "Disclosure under SEBI LODR Regulation 30 for withdrawal of the petition by Rosmerta group.",
    "Intimation of Participation in Investor Meetings dated 27.03.2025, 01.04.2025 and 08.04.2025",
    "Press Release: Ola Electric Commences Deliveries of S1 Gen 3 Scooters Across India.",
    "Clarification on news items appearing in the media to the BSE Limited",
    "Clarification on news items appearing in the media to the National Stock Exchange of India Limited",
    "Media Statement of Ola Electric Mobility Limited dated March 21, 2025.",
    "Intimation under Regulation 30 of SEBI Listing Regulations",
    "Press Release: Ola Electric announces Holi Flash Sale with offers of up to ₹26,750 on its S1 range.",
    "General Update of Ola Electric Mobility Limited",
    "Intimation of Participation in Investor Meetings dated 17.03.25, 18.03.25, 19.03.25, 20.03.25, 21.03.25 and 25.03.25",
    "Disclosure of receipt of Sanction order Ministry of Heavy Industries for Production Linked Incentive Scheme.",
    "Intimation of Participation in Investor Meetings dated 12.03.2025, 13.03.2025, 20.03.2025 and 26.03.2025",
    "Disclosure of receipt of letter from IFCI Limited",
    "Press Release: Ola Electric sells 25,000 units during February 2025; maintains leadership in EV 2Ws with over 28% market share.",
    "Intimation of Participation in Investor Meetings dated 26.02.2025, 04.03.2025 and 06.03.2025",
    "Disclosure of CCPA information submission dated February 19, 2025.",
    "Update on VAHAN Portal registration dated February 19, 2025.",
    "Intimation of Participation in Investor Meetings dated February 20, 2025.",
    "Newspaper Publication of Unaudited Financial Results for the Q3 FY 2024-25.",
    "Outcome of Investors Conference Call for Q3 FY25 February 07, 2025.",
    "Outcome of Board Meeting February 07, 2025.",
    "Product Launch - Ola Electric redefines the motorcycling segment with its all-new Roadster X series",
    "Press Release - Ola Electric redefines the motorcycling segment with its all-new Roadster X series",
    "Prior Intimation of Schedule of Earnings Conference Call Q-3 FY 24-25.",
    "Prior Intimation of Board Meeting Q-3 FY 24-25.",
    "Intimation on founders social media update dated February 03, 2025.",
    "Intimation on founders social media update dated February 02, 2025.",
    "Intimation on founders social media update dated February 01, 2025.",
    "Revised Press Release: Ola Electric leads EV 2W industry with 25% market share records 24,341 registrations in January 2025.",
    "Intimation on first production S1 Pro",
    "Gen 3 S1 Product Launch",
    "Ola Electric takes the S1 Portfolio to the 'Next Level' with Gen 3; launches 8 new scooters across mass and premium segments",
    "Intimation on Gen 3 launching",
    "Intimation on founders social media update",
    "Intimation - updates on the first bike.",
    "Intimation - CCPA further information request.",
    "Intimation - Administrative Warning.",
    "Intimation - Extension by Hon'ble Karnataka High Court.",
    "Intimation - Closure of Trading Window Q-3 F.Y 24-25",
    "Intimation of Appointment of Company Secretary and Compliance Officer.",
    "Intimation of Resignation of Senior Management Personnel.",
    "Intimation - Investors Meet - 12.12.2024.",
    "CCPA Show Cause Notice Update - 05.12.2024.",
    "Intimation - Ola Electric accelerates distribution network to 4,000 stores",
    "Intimation - Investors / Analyst Meet",
    "Newspaper Publication of Unaudited Financial Results Q2 FY25",
    "Monitoring Agency Report",
    "Board Meeting Outcome Nov 08 2024",
    "Invitation to Earnings Call Q2 FY25",
    "Ola Electric BOSS of All Savings",
    "Schedule of Earnings Conference Call - Q2 FY25",
    "Prior Intimation of the Board Meeting - Nov",
    "CCPA show cause notice update",
    "Intimation - Press release on BOSS 72-hour Rush, October 10, 2024",
    "Intimation - Resignation Letter of Company Secretary under Regulation 30, October 05, 2024",
    "Intimation - Regulation 30 Show Cause Notice",
    "Intimation - Press release on BOSS - Biggest Ola Season Sale, October 3, 2024",
    "Postal Ballot Voting Results - Regulation 44 SEBI (LODR) Regulations 2015",
    "Ola Electric launches 'BOSS - Biggest Ola Season Sale'",
    "Intimation - Press Release on PLI Certification - September 27, 2024",
    "Intimation - Press Release on Network Partner Program- September 26, 2024",
    "Intimation - Press Release on #HyperService Campaign - September 27, 2024",
    "Intimation - Resignation of Company Secretary, October 02, 2024",
    "Intimation - PLI Outcome",
    "Intimation - Network Partner Program_FAQs",
    "Update",
    "Intimation - Interaction with the Times of India, September 09, 2024",
    "Postal Ballot Notice",
    "Prior Intimation of the Board Meeting under Regulation 29",
    "Intimation under Regulation 30(5)",
    "Outcome of Board Meeting Q1 FY25",
    "Invitation to Earnings Call Q1 FY25",
    "Intimation - Change in Registered Office of the Company - October 01, 2024",
    "Intimation - Closure of Trading Window - September 27, 2024",
    "Intimation - Participation in a Webinar Session - September 25, 2024",
    "Intimation - Social Media Platforms - September 11, 2024",
  ];

  return (
    <div className="announcements-container">
      <h2 className="announcements-title">Communications to stock exchange</h2>

      {/* Tabs */}
      <div className="announcements-tabs">
        <span className="tab active">Announcements</span>
        <span className="tab inactive">Press Release</span>
      </div>
      <div className="tab-underline"></div>

      {/* List */}
      <div className="announcement-list">
        {announcements.map((item, index) => (
          <div className="announcement-item" key={index}>
            <p className="announcement-text">{item}</p>
            <div className="announcement-right">
              <span className="pdf-text">PDF</span>
              <FaDownload className="download-icon" />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Announcements;
